#pragma once

/*Generated by machine ,Do not edit !!!*/

namespace z10{

namespace R{
    namespace id{
         static constexpr int icon_tongsuo            = 0x00002710 ;/*10000*/
         static constexpr int icon_lvxin              = 0x00002711 ;/*10001*/
         static constexpr int text_top_uv             = 0x00002712 ;/*10002*/
         static constexpr int text_top_tds            = 0x00002713 ;/*10003*/
         static constexpr int icon_zhaoming           = 0x00002714 ;/*10004*/
         static constexpr int text_top_zhileng        = 0x00002715 ;/*10005*/
         static constexpr int text_top_zhibing        = 0x00002716 ;/*10006*/
         static constexpr int text_top_time           = 0x00002717 ;/*10007*/
         static constexpr int icon_wifi               = 0x00002718 ;/*10008*/
         static constexpr int icon_setup              = 0x00002719 ;/*10009*/
         static constexpr int main_content            = 0x0000271A ;/*10010*/
         static constexpr int page                    = 0x0000271B ;/*10011*/
         static constexpr int tab                     = 0x0000271C ;/*10012*/
         static constexpr int linearLayout            = 0x0000271D ;/*10013*/
         static constexpr int title                   = 0x0000271E ;/*10014*/
         static constexpr int lvXin_back              = 0x0000271F ;/*10015*/
         static constexpr int lvXin_arc_HPCC          = 0x00002720 ;/*10016*/
         static constexpr int lvXin_reSet_HPCC        = 0x00002721 ;/*10017*/
         static constexpr int lvXin_arc_RO            = 0x00002722 ;/*10018*/
         static constexpr int lvXin_reSet_RO          = 0x00002723 ;/*10019*/
         static constexpr int lvXin_paiShui           = 0x00002724 ;/*10020*/
         static constexpr int lvXin_congXi            = 0x00002725 ;/*10021*/
         static constexpr int tip                     = 0x00002726 ;/*10022*/
         static constexpr int mode_add_back           = 0x00002727 ;/*10023*/
         static constexpr int mode_add_home           = 0x00002728 ;/*10024*/
         static constexpr int mode_add_enter          = 0x00002729 ;/*10025*/
         static constexpr int setting_mode_listView   = 0x0000272A ;/*10026*/
         static constexpr int mode_add_img            = 0x0000272B ;/*10027*/
         static constexpr int mode_add_name           = 0x0000272C ;/*10028*/
         static constexpr int mode_add_warm_text      = 0x0000272D ;/*10029*/
         static constexpr int mode_add_warm_down      = 0x0000272E ;/*10030*/
         static constexpr int mode_add_warm_up        = 0x0000272F ;/*10031*/
         static constexpr int mode_add_water_text     = 0x00002730 ;/*10032*/
         static constexpr int mode_add_water_down     = 0x00002731 ;/*10033*/
         static constexpr int mode_add_water_up       = 0x00002732 ;/*10034*/
         static constexpr int mode_edit_back          = 0x00002733 ;/*10035*/
         static constexpr int mode_edit_home          = 0x00002734 ;/*10036*/
         static constexpr int mode_edit_del           = 0x00002735 ;/*10037*/
         static constexpr int mode_edit_enter         = 0x00002736 ;/*10038*/
         static constexpr int mode_edit_img           = 0x00002737 ;/*10039*/
         static constexpr int mode_edit_name          = 0x00002738 ;/*10040*/
         static constexpr int mode_edit_warm_text     = 0x00002739 ;/*10041*/
         static constexpr int mode_edit_warm_down     = 0x0000273A ;/*10042*/
         static constexpr int mode_edit_warm_up       = 0x0000273B ;/*10043*/
         static constexpr int mode_edit_water_text    = 0x0000273C ;/*10044*/
         static constexpr int mode_edit_water_down    = 0x0000273D ;/*10045*/
         static constexpr int mode_edit_water_up      = 0x0000273E ;/*10046*/
         static constexpr int netWork_back            = 0x0000273F ;/*10047*/
         static constexpr int setting_network_listView= 0x00002740 ;/*10048*/
         static constexpr int wifi_icon               = 0x00002741 ;/*10049*/
         static constexpr int network_list_name       = 0x00002742 ;/*10050*/
         static constexpr int wifi_lock               = 0x00002743 ;/*10051*/
         static constexpr int wifi_name               = 0x00002744 ;/*10052*/
         static constexpr int page_picture            = 0x00002745 ;/*10053*/
         static constexpr int framelayout_page        = 0x00002746 ;/*10054*/
         static constexpr int page_picture2           = 0x00002747 ;/*10055*/
         static constexpr int page_picture2_btn       = 0x00002748 ;/*10056*/
         static constexpr int arc_wendu               = 0x00002749 ;/*10057*/
         static constexpr int shishiwendu             = 0x0000274A ;/*10058*/
         static constexpr int txt_wendu               = 0x0000274B ;/*10059*/
         static constexpr int min_wendu               = 0x0000274C ;/*10060*/
         static constexpr int max_wendu               = 0x0000274D ;/*10061*/
         static constexpr int arc_chushuiliang        = 0x0000274E ;/*10062*/
         static constexpr int chushuiliang            = 0x0000274F ;/*10063*/
         static constexpr int chushuiliang_reduce     = 0x00002750 ;/*10064*/
         static constexpr int txt_chushuiliang        = 0x00002751 ;/*10065*/
         static constexpr int chushuiliang_add        = 0x00002752 ;/*10066*/
         static constexpr int min_chushuiliang        = 0x00002753 ;/*10067*/
         static constexpr int max_chushuiliang        = 0x00002754 ;/*10068*/
         static constexpr int wendu_reduce            = 0x00002755 ;/*10069*/
         static constexpr int wendu_add               = 0x00002756 ;/*10070*/
         static constexpr int setting_back            = 0x00002757 ;/*10071*/
         static constexpr int setting_screenLight     = 0x00002758 ;/*10072*/
         static constexpr int setting_bt_cryogen      = 0x00002759 ;/*10073*/
         static constexpr int setting_washTime        = 0x0000275A ;/*10074*/
         static constexpr int setting_bt_ice          = 0x0000275B ;/*10075*/
         static constexpr int setting_modechoose      = 0x0000275C ;/*10076*/
         static constexpr int setting_bt_lock         = 0x0000275D ;/*10077*/
         static constexpr int setting_net             = 0x0000275E ;/*10078*/
         static constexpr int setting_time            = 0x0000275F ;/*10079*/
         static constexpr int setting_uv              = 0x00002760 ;/*10080*/
         static constexpr int setting_lvxin           = 0x00002761 ;/*10081*/
         static constexpr int setting_version         = 0x00002762 ;/*10082*/
         static constexpr int setting_reset           = 0x00002763 ;/*10083*/
         static constexpr int icon_back               = 0x00002764 ;/*10084*/
         static constexpr int numberpicker_set_year   = 0x00002765 ;/*10085*/
         static constexpr int numberpicker_set_mon    = 0x00002766 ;/*10086*/
         static constexpr int numberpicker_set_day    = 0x00002767 ;/*10087*/
         static constexpr int numberpicker_set_hour   = 0x00002768 ;/*10088*/
         static constexpr int numberpicker_set_min    = 0x00002769 ;/*10089*/
         static constexpr int btn_set_time_cancle     = 0x0000276A ;/*10090*/
         static constexpr int btn_set_time_verify     = 0x0000276B ;/*10091*/
         static constexpr int unlock_progressBar      = 0x0000276C ;/*10092*/
         static constexpr int btn_keep                = 0x0000276D ;/*10093*/
         static constexpr int checkbox_keep_uv_mode   = 0x0000276E ;/*10094*/
         static constexpr int checkbox_set_uv_time    = 0x0000276F ;/*10095*/
         static constexpr int numberpicker_star_hour  = 0x00002770 ;/*10096*/
         static constexpr int numberpicker_star_min   = 0x00002771 ;/*10097*/
         static constexpr int numberpicker_end_hour   = 0x00002772 ;/*10098*/
         static constexpr int numberpicker_end_min    = 0x00002773 ;/*10099*/
         static constexpr int relative_initiative_uv  = 0x00002774 ;/*10100*/
         static constexpr int checkbox_initiative_uv  = 0x00002775 ;/*10101*/
         static constexpr int btn_nowshajun           = 0x00002776 ;/*10102*/
         static constexpr int mode_del_Box            = 0x00002777 ;/*10103*/
         static constexpr int mode_del_title          = 0x00002778 ;/*10104*/
         static constexpr int mode_del_warm           = 0x00002779 ;/*10105*/
         static constexpr int mode_del_water          = 0x0000277A ;/*10106*/
         static constexpr int mode_del_cancel         = 0x0000277B ;/*10107*/
         static constexpr int mode_del_enter          = 0x0000277C ;/*10108*/
         static constexpr int popwindow_Box           = 0x0000277D ;/*10109*/
         static constexpr int popwindow_hint_text     = 0x0000277E ;/*10110*/
         static constexpr int popwindow_hint_cancel   = 0x0000277F ;/*10111*/
         static constexpr int popwindow_hint_enter    = 0x00002780 ;/*10112*/
         static constexpr int popwindow_tip_text      = 0x00002781 ;/*10113*/
         static constexpr int popwindow_tip_text2     = 0x00002782 ;/*10114*/
         static constexpr int popwindow_tip_text3     = 0x00002783 ;/*10115*/
         static constexpr int popwindow_tip_hint_enter= 0x00002784 ;/*10116*/
         static constexpr int setting_screenLight_Box = 0x00002785 ;/*10117*/
         static constexpr int setting_seekbar         = 0x00002786 ;/*10118*/
         static constexpr int setting_screenLight_cancel= 0x00002787 ;/*10119*/
         static constexpr int setting_screenLight_enter= 0x00002788 ;/*10120*/
         static constexpr int mode_back               = 0x00002789 ;/*10121*/
         static constexpr int setting_modeadd         = 0x0000278A ;/*10122*/
         static constexpr int mode_img                = 0x0000278B ;/*10123*/
         static constexpr int mode_name               = 0x0000278C ;/*10124*/
         static constexpr int mode_warm               = 0x0000278D ;/*10125*/
         static constexpr int mode_water              = 0x0000278E ;/*10126*/
         static constexpr int mode_turnleft           = 0x0000278F ;/*10127*/
         static constexpr int mode_del                = 0x00002790 ;/*10128*/
         static constexpr int mode_turnright          = 0x00002791 ;/*10129*/
         static constexpr int seting_switch_time_fromat= 0x00002792 ;/*10130*/
         static constexpr int linear_test             = 0x00002793 ;/*10131*/
         static constexpr int linear                  = 0x00002794 ;/*10132*/
         static constexpr int numberpicker            = 0x00002795 ;/*10133*/
         static constexpr int listView                = 0x00002796 ;/*10134*/
    };/*namespace id*/

    namespace strings{
    };/*namespace strings*/

};//endof namespace R

}//endof namespace

